In [1]:
import numpy as np


In [2]:
7**4

2401

In [3]:
7//4

1

In [4]:
x = "hey, there, rudra"
print(x.split(","))

['hey', ' there', ' rudra']


In [6]:
planet = "Earth"
diameter = 12742
print("the diameter of {} is {} kilometer".format(planet,diameter))

the diameter of Earth is 12742 kilometer


In [9]:
lst = [1,2,[3,4],[5,[100,200,["hello"]],23,11],1,7]
print(lst[3][1][2][0])

hello


In [14]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [15]:
"list allows duplicate values tuple does not"

'list allows duplicate values tuple does not'

In [30]:
email="rudramakwana3117@gmail.com" 

print(email.split('@')[1])


gmail.com


In [37]:
a = "is there a dog here"
print("dog" in a)

True


In [1]:
import numpy as np 

In [2]:
np._version__

AttributeError: module 'numpy' has no attribute '_version__'

In [3]:
np.__version__

'1.26.4'

In [4]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [5]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [6]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [7]:
arr = np.arrange(0,51)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
arr = np.arange(0,51)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [11]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [12]:
np.arange(0,101,4)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [13]:
np.arange(-100,101,2)

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80,
        -78,  -76,  -74,  -72,  -70,  -68,  -66,  -64,  -62,  -60,  -58,
        -56,  -54,  -52,  -50,  -48,  -46,  -44,  -42,  -40,  -38,  -36,
        -34,  -32,  -30,  -28,  -26,  -24,  -22,  -20,  -18,  -16,  -14,
        -12,  -10,   -8,   -6,   -4,   -2,    0,    2,    4,    6,    8,
         10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100])

In [16]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.arange[(3,3)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [18]:
np.arange[(3,3),[(3,3)]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [19]:
np.arange[(3,3)[(3,3)]]

<>:1: SyntaxWarning: tuple indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: tuple indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Rudra\AppData\Local\Temp\ipykernel_11836\1902279683.py:1: SyntaxWarning: tuple indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.arange[(3,3)[(3,3)]]


TypeError: tuple indices must be integers or slices, not tuple

In [20]:
np.arange[3,3]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [21]:
np.arange([1,2,3],[4,5,6])

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [22]:
np.arange([0,1,2,3,4])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [23]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [ ]:
np.arange[(3,3),[(3,3)]]