In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

In [6]:
pd?

Type:        module
String form: <module 'pandas' from 'C:\\Users\\Rudra\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\rudra\appdata\local\programs\python\python312\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non

In [10]:
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype: 'Dtype | None' = None,
    name=None,
    copy: 'bool | None' = None,
    fastpath: 'bool | lib.NoDefault' = <no_default>,
) -> 'None'
Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, \*, \*\*) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series. If data is a dict, argument order is
    maintained.
index : array-like or Index (1d)
    

In [9]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [11]:
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [12]:
s1 = pd.Series([1,2,3],index = ['a','b','c'])
s1

a    1
b    2
c    3
dtype: int64

In [15]:
s1 = pd.Series(['a','b','c'],index = [1,2,3])
s1

1    a
2    b
3    c
dtype: object

In [17]:
pd.Series([30,50,90],index = ['ds','calculus','tableau'])

ds          30
calculus    50
tableau     90
dtype: int64

In [26]:
s2 = pd.Series(['A+','B+','C+','D+'],['rudra','kishan','samarth','xyz'])
s2

rudra      A+
kishan     B+
samarth    C+
xyz        D+
dtype: object

In [1]:
import pandas as pd

In [2]:
pd.Series((1,2,3,4,4))

0    1
1    2
2    3
3    4
4    4
dtype: int64

In [5]:
pd.Series({1,2,3,4})

TypeError: 'set' type is unordered

In [6]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [10]:
pd.DataFrame({'Rudra':[54,53],'kishan':[89,34],'samarth':[54,76]},index = ['Python','FDS',])

Rudra  kishan  samarth
Python     54      89       54
FDS        53      34       76

In [12]:
pd.DataFrame([[24,23],[45,46]],columns = ['A','B'],index = ['PY','DS'])

A   B
PY  24  23
DS  45  46

In [13]:
import numpy as np

In [15]:
pd.DataFrame(np.random.randint(0,30,(3,3)),index = ['rud','kish','sam'],columns = ['PY','FD','CA'])

PY  FD  CA
rud    5   7  14
kish  25   1  10
sam   19  22   7

In [16]:
np.random.seed(9)

In [17]:
marks


NameError: name 'marks' is not defined

In [18]:
marks = pd.DataFrame(np.random.randint(0,30,(3,3)),index = ['rud','kish','sam'],columns = ['PY','FD','CA'])

In [20]:
marks

PY  FD  CA
rud   28  21  22
kish  24  27  22
sam   29   1  22

In [21]:
marks.columns

Index(['PY', 'FD', 'CA'], dtype='object')

In [22]:
marks.index

Index(['rud', 'kish', 'sam'], dtype='object')

In [23]:
marks['PY']

rud     28
kish    24
sam     29
Name: PY, dtype: int32

In [24]:
marks['FD']

rud     21
kish    27
sam      1
Name: FD, dtype: int32

In [26]:
marks.loc['rud']

PY    28
FD    21
CA    22
Name: rud, dtype: int32

In [40]:
marks['TOTAL'] = marks['PY']+marks['FD']+marks['CA']

In [41]:
marks

PY  FD  CA  TOTAL   per
rud   28  21  22     71  53.4
kish  24  27  22     73  55.4
sam   29   1  22     52  34.4

In [42]:
#indexing & selection

In [47]:
marks[['PY','CA']]

PY  CA
rud   28  22
kish  24  22
sam   29  22

In [50]:
#loc,iloc,ix

In [56]:
pd.DataFrame

pandas.core.frame.DataFrame

In [61]:
marks.loc['rud',['PY','CA']]

PY    28.0
CA    22.0
Name: rud, dtype: float64

In [62]:
marks.loc['sam','PY':'CA']

PY    29.0
FD     1.0
CA    22.0
Name: sam, dtype: float64

In [63]:
marks.iloc[:2,0:3]

PY  FD  CA
rud   28  21  22
kish  24  27  22

#### marks.iloc[:3,1:]

In [74]:
marks.iloc[0:3,3:4]

TOTAL
rud      71
kish     73
sam      52

# ASSGNIMENT

In [79]:
pd.DataFrame(np.random.randint(10,100,(3,3)),index = ['rud','sam','kish'],columns = ['phy','maths','python'])

phy  maths  python
rud    43     87      64
sam    73     32      60
kish   50     14      62

In [89]:
np.random.seed(12)

In [102]:
result= pd.DataFrame(np.random.randint(10,100,(3,3)),index = ['rud','sam','kish'],columns = ['phy','maths','python'])

In [104]:
np.random.seed(14)
result

phy  maths  python
rud    85     37      16
sam    12     13      77
kish   86     58      32

In [105]:
result

phy  maths  python
rud    85     37      16
sam    12     13      77
kish   86     58      32

In [108]:
result[result.python<41]=41

In [111]:
result[result.loc[:,'maths':'maths']<40]=41

In [112]:
result

phy  maths  python
rud    41     41      41
sam    12     41      77
kish   41     41      41

In [2]:
import pandas as pd

In [3]:
product_id = ['P001', 'P002', 'P003', 'P004', 'P005']
product_name = ['mobile', 'tabl', 'Jeans', 'Hat', 'Shoes']
product_price = [19.99, 29.99, 39.99, 14.99, 49.99]
df = pd.DataFrame({'productId': product_id, 'ProductName': product_name, 'ProductPrice': product_price})

print(df)

  productId ProductName  ProductPrice
0      P001      mobile         19.99
1      P002        tabl         29.99
2      P003       Jeans         39.99
3      P004         Hat         14.99
4      P005       Shoes         49.99


# 20-9-2024

In [5]:
import numpy as np

In [15]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser


0    6
1    3
2    7
3    4
dtype: int32

In [16]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [18]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns = ['A','B','C','D'])

In [19]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [23]:
area = pd.Series({'UP':243286,'M':307713,'B':94136},name = 'area')
population = pd.Series({'WB':91276115,'M':124484447,'B':104099452},name='population')


In [25]:
population_density = population/area
population_density

B     1105.841038
M      404.547247
UP            NaN
WB            NaN
dtype: float64

In [27]:
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index = [1,2,3])

In [28]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [30]:
X = pd.DataFrame(rng.randint(0,15,(2,2)),columns=list('XY'))
Y = pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('YZX'))

In [31]:
X+Y

X     Y   Z
0   5.0  12.0 NaN
1  16.0  13.0 NaN
2   NaN   NaN NaN

In [33]:
fill = X.stack().mean()
X.add(Y,fill_value = fill)

X     Y     Z
0   5.0  12.0   9.0
1  16.0  13.0  17.0
2  17.0  16.0   8.0

In [34]:
np.random.RandomState?

Init signature: np.random.RandomState(self, /, *args, **kwargs)
Docstring:     
RandomState(seed=None)

Container for the slow Mersenne Twister pseudo-random number generator.
Consider using a different BitGenerator with the Generator container
instead.

`RandomState` and `Generator` expose a number of methods for generating
random numbers drawn from a variety of probability distributions. In
addition to the distribution-specific arguments, each method takes a
keyword argument `size` that defaults to ``None``. If `size` is ``None``,
then a single value is generated and returned. If `size` is an integer,
then a 1-D array filled with generated values is returned. If `size` is a
tuple, then an array with that shape is filled and returned.

**Compatibility Guarantee**

A fixed bit generator using a fixed seed and a fixed series of calls to
'RandomState' methods using the same parameters will always produce the
same results up to roundoff error except when the values were incorrect.
`Random

In [35]:
A = np.random.randint(10,size=(3,4))

In [36]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-8,  5,  3, -1],
       [-8,  5, -3, -3]], dtype=int32)

In [37]:
A

array([[8, 1, 6, 5],
       [0, 6, 9, 4],
       [0, 6, 3, 2]], dtype=int32)

In [38]:
df = pd.DataFrame(A,columns = list('QRST'))

In [39]:
df

Q  R  S  T
0  8  1  6  5
1  0  6  9  4
2  0  6  3  2

In [40]:
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -8  5  3 -1
2 -8  5 -3 -3

In [42]:
df.subtract(df['R'],axis = 0)

Q  R  S  T
0  7  0  5  4
1 -6  0  3 -2
2 -6  0 -3 -4

In [49]:
halfrow = df.iloc[0,::2]

In [50]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -8.0 NaN  3.0 NaN
2 -8.0 NaN -3.0 NaN

In [51]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np.min(a)

np.int64(1)

In [56]:
a[1,1]=49
a

array([[ 1,  2],
       [ 3, 49],
       [ 5,  6]])

In [61]:
a.transpose()

array([[ 1,  3,  5],
       [ 2, 49,  6]])

In [58]:
a

array([[ 1,  2],
       [ 3, 49],
       [ 5,  6]])

In [60]:
a[0:1,]

array([[1, 2]])

#27-09-24

In [1]:
import pandas as pd

In [2]:
import numpy as np 

In [4]:
val = np.array([1,None,2,3])
val

array([1, None, 2, 3], dtype=object)

In [5]:
%timeit np.arange(1E6,dtype=int).sum()

5.5 ms ± 461 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit np.arange(1E6,dtype=object).sum()

118 ms ± 9.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
val.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [8]:
val1 = np.array([1,np.nan,3,4])
val1

array([ 1., nan,  3.,  4.])

In [13]:
1 + np.nan

nan

In [14]:
0*np.nan

nan

In [15]:
val1.sum(),val1.min(),val1.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [16]:
np.nansum(val1)

np.float64(8.0)

In [17]:
np.nanmin(val1),np.nanmax(val1)

(np.float64(1.0), np.float64(4.0))

In [18]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [27]:
pd.Series([None,2,3],dtype="Int32")

0    <NA>
1       2
2       3
dtype: Int32

In [3]:
data = pd.Series([1,np.nan,'hello',None])

In [5]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [6]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [8]:
df = pd.DataFrame([[1, np.nan,2],[2,3,5],[np.nan,4,6]])

In [10]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [11]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [12]:
df.dropna(axis = 'columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [14]:
df.dropna(axis = 'rows',thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

In [15]:
df.dropna(axis = 'columns',thresh = 3)

2
0  2
1  5
2  6

In [28]:
data3 = pd.Series([1,np.nan,2,None,3],index = list('abcde'),dtype = 'Int32')
data3

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [30]:
data3.ffill()

a    1
b    1
c    2
d    2
e    3
dtype: Int32

1-10-2024

In [1]:
import pandas as pd

In [2]:
import numpy as np 

In [3]:
series = pd.Series([5, 10, np.nan, 20, 15])
series

0     5.0
1    10.0
2     NaN
3    20.0
4    15.0
dtype: float64

In [4]:
sum_series = series.sum()
sum_series

np.float64(50.0)

In [5]:
mean_series = series.mean()
mean_series

np.float64(12.5)

In [6]:
min_value = series.min()
min_value

np.float64(5.0)

In [15]:
min_value = series.min()
min_value

np.float64(5.0)

In [16]:
isnull_values = series.isnull()
isnull_values

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [18]:
notnull_values = series.notnull()
notnull_values

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [7]:
data = {'A': [1, np.nan, 3, 4], 'B': [np.nan, 2, 3, 4]}
df = pd.DataFrame(data)
data

{'A': [1, nan, 3, 4], 'B': [nan, 2, 3, 4]}

In [8]:
df

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  4.0  4.0

In [9]:
df_drop_columns = df.dropna(axis=1)
df_drop_columns

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [11]:
df['C'] = [np.nan, 5, np.nan, 7]

In [12]:
df['C']

0    NaN
1    5.0
2    NaN
3    7.0
Name: C, dtype: float64

In [13]:
df_ffill_columns = df.ffill(axis=0)
df_ffill_columns

A    B    C
0  1.0  NaN  NaN
1  1.0  2.0  5.0
2  3.0  3.0  5.0
3  4.0  4.0  7.0

In [14]:
df_bfill_rows = df.bfill(axis=1)
df_bfill_rows

A    B    C
0  1.0  NaN  NaN
1  2.0  2.0  5.0
2  3.0  3.0  NaN
3  4.0  4.0  7.0